# Gunakan image Python sebagai dasar
FROM python:3.9

# Set kerjaan direktori
WORKDIR /app

# Salin file-file yang diperlukan
COPY app.py /app
COPY requirements.txt /app

# Install dependensi Python
RUN pip install -r requirements.txt

# Expose port yang digunakan oleh aplikasi Flask
EXPOSE 5000

# Perintah untuk menjalankan aplikasi Flask pada port 5000
CMD ["python", "app.py"]